### ISSUE TITLE
Comentarios avance1

### ISSUE THREAD

**Issue by AliciaMstt** [madisson-luna/Proyecto_Final-Bioinf2017-II#1]
OK

Se ve padre 👍

**Comment by madisson-luna** [comment]
Ok 

Gracias, ahora que la fuerza y el codigo este conmigo jajaja

**Comment by AliciaMstt** [comment]
No olvides cerrar este issue.

**Comment by AzaleaGuerra** [comment]
En el repositorio no se encuentran los datos crudos, por tanto, no puedes hacer el preprocesamiento y los datos ya están mapeados, por lo que sólo podrás concentrarte en la parte de genética de poblaciones.

**Comment by madisson-luna** [comment]
Si acabo de notarlo hoy que descargue los datos de Dryad, es necesario que intente hacer más análisis además de los de genética de poblaciones?

**Comment by AliciaMstt** [comment]
Puedes intentar nuevos análisis, pero si lo que quieres es practicar el mapeo, entonces puedes cambiar de set de datos. 

Abre de nuevo este issue hasta que resuelvas eso.
