### ISSUE TITLE
comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [madisson-luna/Proyecto_Final-Bioinf2017-II#2]
OK 

¿No tuviste problemas con instalar Stacks en docker y la MSQL?

**Comment by madisson-luna** [comment]
pues fue algo complicado pero primero lo primero que hice en el contenedor fue apt-gate update
después intenté correr ./configure en el contenedor desde el folder de Stacks pero no corria y se soluciono cuando hice:
apt-get install build-essential
apt-get install zlib1g-dev
y enseguida 
./configure
make
make install

parece que todo salio bien mira:
https://github.com/madisson-luna/Tareas-Curso-BioinfInvRepro/blob/master/Screenshot%20from%20InstallSatacks.png

**Comment by AliciaMstt** [comment]
Se ve bien, pero intenta correrloc on los datos del tutorial de la página para asegurarte que todo esté bien. MySQL es tricky.

**Comment by madisson-luna** [comment]
tienes razón saca un error
mysql: [ERROR] Fatal error in defaults handling. Program aborted!
mysql: [ERROR] Could not open required defaults file: /usr/local/share/stacks/sql/mysql.cnf

pero ya modifiqué el archivo mysql.cnf y todo como viene en el manual de stacks 
Tienes alguna sugerencia?

**Comment by madisson-luna** [comment]
creo que lo solucioné pero ahora sale este error
ERROR 1045 (28000): Access denied for user 'madisson'@'localhost' (using password: YES)
sabes porqué?

**Comment by AliciaMstt** [comment]
Es el problema más común de instalación de Stacks, googlea ese error y te saldrán resultados en el foro. Si para el martes no lo logras resolver avísame y te paso lo que hicimos para instalarlo en conabio.

**Comment by madisson-luna** [comment]
creo que ya resolví ese problema pero ahora tengo otro =/ 
ERROR 1046 (3D000) at line 1: No database selected
lo busqué en stacks overflow pero la verdad no entiendo como resolverlo, podemos verlo mañana después de clase?
Mientras tanto estoy intentando con un contenedor de samtools jaja (Plan B)

**Comment by AliciaMstt** [comment]
Busca no en stacksoverflow sino en el google groups de stacks users. Sin ver tu código (siempre que pongas un error pon el código que lo produjo) creo que te faltó utilizar el flag -D o -B. Checa los tutoriales de Stacks.

**Comment by madisson-luna** [comment]
Ya quedó instalado Alicia, Chris me ayudó y pudimos instalarlo ahora si por completo, además creo que había un error en la pipeline que corrí. 
Muchas gracias, espero poder avanzar más rápido en el proyecto
